// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQYmVBgAWj3BGSUfZFRMgvCLaWzbKmFa0',
    appId: '1:190678389740:web:1b2649b364d9eb93c626c9',
    messagingSenderId: '190678389740',
    projectId: 'agendarcitasflutter',
    authDomain: 'agendarcitasflutter.firebaseapp.com',
    storageBucket: 'agendarcitasflutter.firebasestorage.app',
    measurementId: 'G-7TW1EV4XRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfWGow62e294piMGoAjf2q--kwZT2nwbk',
    appId: '1:190678389740:android:985524a9bd0c16c3c626c9',
    messagingSenderId: '190678389740',
    projectId: 'agendarcitasflutter',
    storageBucket: 'agendarcitasflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP1C0rPfgOFYHnv1l_MYJmYeMA5tfBIYk',
    appId: '1:190678389740:ios:6a0da30c572b393cc626c9',
    messagingSenderId: '190678389740',
    projectId: 'agendarcitasflutter',
    storageBucket: 'agendarcitasflutter.firebasestorage.app',
    iosBundleId: 'com.utpl.agendarcitasflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP1C0rPfgOFYHnv1l_MYJmYeMA5tfBIYk',
    appId: '1:190678389740:ios:6a0da30c572b393cc626c9',
    messagingSenderId: '190678389740',
    projectId: 'agendarcitasflutter',
    storageBucket: 'agendarcitasflutter.firebasestorage.app',
    iosBundleId: 'com.utpl.agendarcitasflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQYmVBgAWj3BGSUfZFRMgvCLaWzbKmFa0',
    appId: '1:190678389740:web:ee12d7dcb0d5d942c626c9',
    messagingSenderId: '190678389740',
    projectId: 'agendarcitasflutter',
    authDomain: 'agendarcitasflutter.firebaseapp.com',
    storageBucket: 'agendarcitasflutter.firebasestorage.app',
    measurementId: 'G-M10EGM15KP',
  );
}
