name: Firebase App Distribution

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: "beta"
      - name: Run Flutter
        run: |
          flutter pub get
          flutter analyze      
        # flutter test
      - run: flutter build apk
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{github.run_number}}
          token: ${{ secrets.GIT_TOKEN }}
      - name: upload artifact to Fiebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Administradores
          file: build/app/outputs/apk/release/app-release.apk

  slackNotification:
      name: Slack Notification
      runs-on: ubuntu-latest
      needs: [build]
      if: success()
      steps:
        - name: Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
            SLACK_MESSAGE: 'Código de la aplicación móvil analizado exitosamente y desplegado en Firebase App Distribution'